In [1]:
import cv2
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Model, load_model

In [2]:
model = load_model('model-001.model')

In [3]:
# label dictionary for each image class and color dictionary for bounding boxes
labels_dict = {0:'correctly_worn', 1:'incorrectly_worn', 2:'no_mask'}
color_dict = {0:(0,255,0), 1:(255,255,0), 2:(0,0,255)}

In [4]:
# import face detection program

classifier = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')

In [5]:
size = 4
webcam = cv2.VideoCapture(0)

while True:
    (rval, im) = webcam.read()
    im=cv2.flip(im,1,1)
    
    mini = cv2.resize(im, (im.shape[1] // size, im.shape[0] // size))
    
    faces = classifier.detectMultiScale(mini)
    
    for f in faces:
        (x, y, w, h) = [v * size for v in f]
        face_img = im[y:y+h, x:x+w]
        resized = cv2.resize(face_img, (150,150))
        normalized = resized/255.0
        reshaped=np.reshape(normalized,(1,150,150,3))
        reshaped= np.vstack([reshaped])
        result = model.predict(reshaped)
        print(result)
        
        label = np.argmax(result,axis=1)[0]
        
        cv2.rectangle(im,(x,y),(x+w,y+h),color_dict[label],2)
        cv2.rectangle(im,(x,y-40),(x+w,y),color_dict[label],-1)
        cv2.putText(im,labels_dict[label], (x, y-10),cv2.FONT_HERSHEY_SIMPLEX,0.8,(255,255,255),2)
        
    cv2.imshow('LIVE', im)
    key = cv2.waitKey(10)
    if key == 27: # ESC key
        break
        
webcam.release()

cv2.destroyAllWindows()

[[1.4436964e-04 1.9121101e-03 9.9794346e-01]]
[[1.09196335e-04 1.63167587e-03 9.98259127e-01]]
[[1.6316463e-04 2.2220840e-03 9.9761474e-01]]
[[1.7915509e-04 2.3586701e-03 9.9746215e-01]]
[[1.8266602e-04 2.5192965e-03 9.9729806e-01]]
[[1.8157749e-04 2.1154077e-03 9.9770302e-01]]
[[1.6609191e-04 2.2255087e-03 9.9760842e-01]]
[[2.6115187e-04 3.2957213e-03 9.9644309e-01]]
[[2.1255354e-04 2.8104992e-03 9.9697697e-01]]
[[1.7039817e-04 2.2924631e-03 9.9753714e-01]]
[[2.5218393e-04 3.2807423e-03 9.9646711e-01]]
[[1.8828672e-04 2.7480156e-03 9.9706370e-01]]
[[1.9275954e-04 2.8879966e-03 9.9691927e-01]]
[[2.8485007e-04 3.1748861e-03 9.9654031e-01]]
[[2.6187103e-04 3.2079904e-03 9.9653012e-01]]
[[2.4138024e-04 3.1986106e-03 9.9656004e-01]]
[[2.4109997e-04 3.4308534e-03 9.9632806e-01]]
[[2.5335714e-04 2.9745505e-03 9.9677211e-01]]
[[2.2944462e-04 3.2230758e-03 9.9654752e-01]]
[[1.6722632e-04 2.0993119e-03 9.9773347e-01]]
[[1.6079230e-04 2.0993894e-03 9.9773979e-01]]
[[1.6960027e-04 2.2822951e-03 9

In [6]:
model.predict()

TypeError: predict() missing 1 required positional argument: 'x'